name: Auto Deploy to EasyPanel

on:
  push:
    branches:
      - main  # Solo deploya cuando hagas push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger EasyPanel Deploy
        run: |
          curl -X POST http://206.183.130.17:3000/api/deploy/a2970e5dff930a255ce8c80dd7b965b5a1fe474504ea1e56
